export const CART_ACTIONS_TYPES = {
    IS_CART_OPEN: "IS_CART_OPEN",
    ADD_ITEM_TO_CART: "ADD_ITEM_TO_CART",
    REMOVE_ITEM_FROM_CART: "REMOVE_ITEM_FROM_CART",
    DELETE_ITEM_FROM_CART: "DELETE_ITEM_FROM_CART",
  };